#ifndef EEPP_GRAPHICS_HPP
#define EEPP_GRAPHICS_HPP

#include <eepp/graphics/renderer/renderer.hpp>
#include <eepp/graphics/blendmode.hpp>
#include <eepp/graphics/pixeldensity.hpp>
#include <eepp/graphics/renderer/renderergl.hpp>
#include <eepp/graphics/renderer/renderergl3.hpp>
#include <eepp/graphics/graphicshelper.hpp>
#include <eepp/graphics/image.hpp>
#include <eepp/graphics/texture.hpp>
#include <eepp/graphics/textureloader.hpp>
#include <eepp/graphics/texturefactory.hpp>
#include <eepp/graphics/texturepacker.hpp>
#include <eepp/graphics/subtexture.hpp>
#include <eepp/graphics/textureatlas.hpp>
#include <eepp/graphics/globaltextureatlas.hpp>
#include <eepp/graphics/textureatlasmanager.hpp>
#include <eepp/graphics/drawablesearcher.hpp>
#include <eepp/graphics/sprite.hpp>
#include <eepp/graphics/particle.hpp>
#include <eepp/graphics/particlesystem.hpp>
#include <eepp/graphics/fontstyleconfig.hpp>
#include <eepp/graphics/font.hpp>
#include <eepp/graphics/fonttruetype.hpp>
#include <eepp/graphics/fonttruetypeloader.hpp>
#include <eepp/graphics/fontmanager.hpp>
#include <eepp/graphics/text.hpp>
#include <eepp/graphics/primitives.hpp>
#include <eepp/graphics/scrollparallax.hpp>
#include <eepp/graphics/console.hpp>
#include <eepp/graphics/batchrenderer.hpp>
#include <eepp/graphics/globalbatchrenderer.hpp>
#include <eepp/graphics/shader.hpp>
#include <eepp/graphics/shaderprogram.hpp>
#include <eepp/graphics/shaderprogrammanager.hpp>
#include <eepp/graphics/textureatlasloader.hpp>
#include <eepp/graphics/framebuffer.hpp>
#include <eepp/graphics/vertexbuffer.hpp>
#include <eepp/graphics/vertexbufferogl.hpp>
#include <eepp/graphics/vertexbuffervbo.hpp>
#include <eepp/graphics/arcdrawable.hpp>
#include <eepp/graphics/circledrawable.hpp>
#include <eepp/graphics/rectangledrawable.hpp>

#endif
