#ifndef EEPP_GRAPHICS_HPP
#define EEPP_GRAPHICS_HPP

#include <eepp/graphics/renderer/cgl.hpp>
#include <eepp/graphics/blendmode.hpp>
#include <eepp/graphics/renderer/crenderergl.hpp>
#include <eepp/graphics/renderer/crenderergl3.hpp>
#include <eepp/graphics/renders.hpp>
#include <eepp/graphics/cimage.hpp>
#include <eepp/graphics/ctexture.hpp>
#include <eepp/graphics/ctextureloader.hpp>
#include <eepp/graphics/ctexturefactory.hpp>
#include <eepp/graphics/ctexturepacker.hpp>
#include <eepp/graphics/csubtexture.hpp>
#include <eepp/graphics/ctextureatlas.hpp>
#include <eepp/graphics/cglobaltextureatlas.hpp>
#include <eepp/graphics/ctextureatlasmanager.hpp>
#include <eepp/graphics/csprite.hpp>
#include <eepp/graphics/cparticle.hpp>
#include <eepp/graphics/cparticlesystem.hpp>
#include <eepp/graphics/cfont.hpp>
#include <eepp/graphics/ctexturefont.hpp>
#include <eepp/graphics/cttffont.hpp>
#include <eepp/graphics/ctexturefontloader.hpp>
#include <eepp/graphics/cttffontloader.hpp>
#include <eepp/graphics/cfontmanager.hpp>
#include <eepp/graphics/cprimitives.hpp>
#include <eepp/graphics/cscrollparallax.hpp>
#include <eepp/graphics/cconsole.hpp>
#include <eepp/graphics/cbatchrenderer.hpp>
#include <eepp/graphics/cglobalbatchrenderer.hpp>
#include <eepp/graphics/ctextcache.hpp>
#include <eepp/graphics/pixelperfect.hpp>
#include <eepp/graphics/cshader.hpp>
#include <eepp/graphics/cshaderprogram.hpp>
#include <eepp/graphics/cshaderprogrammanager.hpp>
#include <eepp/graphics/ctextureatlasloader.hpp>
#include <eepp/graphics/cframebuffer.hpp>
#include <eepp/graphics/cvertexbuffer.hpp>
#include <eepp/graphics/cvertexbufferogl.hpp>
#include <eepp/graphics/cvertexbuffervbo.hpp>

#endif
