#ifndef EE_GAMINGMAPHELPER_HPP
#define EE_GAMINGMAPHELPER_HPP

namespace EE { namespace Gaming {

class GObjFlags {
	public:
		enum EE_GAMEOBJECT_FLAGS {
			GAMEOBJECT_STATIC		=  ( 1 << 0 ),
			GAMEOBJECT_ANIMATED		=  ( 1 << 1 ),
			GAMEOBJECT_MIRRORED		=  ( 1 << 2 ),
			GAMEOBJECT_FLIPED		=  ( 1 << 3 ),
			GAMEOBJECT_BLOCKED		=  ( 1 << 4 )
		};
};

enum EE_GAMEOBJECT_TYPE {
	GAMEOBJECT_TYPE_BASE,
	GAMEOBJECT_TYPE_SHAPE,
	GAMEOBJECT_TYPE_SHAPEEX,
	GAMEOBJECT_TYPE_SPRITE,
	GAMEOBJECT_TYPE_USER = 100
};

enum EE_LAYER_TYPE {
	MAP_LAYER_TILED,
	MAP_LAYER_OBJECT
};

enum EE_MAP_FLAGS {
	MAP_FLAG_CLAMP_BODERS	= ( 1 << 0 ),
	MAP_FLAG_CLIP_AREA		= ( 1 << 1 )
};

}}

#endif
