#ifndef EE_WINDOWCURSORHELPER_HPP
#define EE_WINDOWCURSORHELPER_HPP

namespace EE { namespace Window { namespace Cursor {

enum EE_SYSTEM_CURSOR {
   SYS_CURSOR_NONE        =  0,
   SYS_CURSOR_DEFAULT     =  1,
   SYS_CURSOR_ARROW       =  2,
   SYS_CURSOR_BUSY        =  3,
   SYS_CURSOR_QUESTION    =  4,
   SYS_CURSOR_EDIT        =  5,
   SYS_CURSOR_MOVE        =  6,
   SYS_CURSOR_RESIZE_N    =  7,
   SYS_CURSOR_RESIZE_W    =  8,
   SYS_CURSOR_RESIZE_S    =  9,
   SYS_CURSOR_RESIZE_E    = 10,
   SYS_CURSOR_RESIZE_NW   = 11,
   SYS_CURSOR_RESIZE_SW   = 12,
   SYS_CURSOR_RESIZE_SE   = 13,
   SYS_CURSOR_RESIZE_NE   = 14,
   SYS_CURSOR_PROGRESS    = 15,
   SYS_CURSOR_PRECISION   = 16,
   SYS_CURSOR_LINK        = 17,
   SYS_CURSOR_ALT_SELECT  = 18,
   SYS_CURSOR_UNAVAILABLE = 19,
   SYS_CURSOR_COUNT
};

}}}

#endif
 
